

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);


CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_key
    ON users (lower(btrim(username)));


CREATE TABLE IF NOT EXISTS search_history (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind          TEXT        NOT NULL,
    query         TEXT        NOT NULL,
    filters       JSONB       NOT NULL DEFAULT '{}'::jsonb,

    last_page     INTEGER     NOT NULL DEFAULT 1,
    size          INTEGER     NOT NULL DEFAULT 20,
    result_total  INTEGER,

    search_count  INTEGER     NOT NULL DEFAULT 1,

    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT search_history_kind_known        CHECK (kind IN ('oirf', 'report')),
    CONSTRAINT search_history_last_page_positive CHECK (last_page >= 1),
    CONSTRAINT search_history_size_positive     CHECK (size >= 1),
    CONSTRAINT search_history_count_positive    CHECK (search_count >= 1),
    CONSTRAINT search_history_seen_order        CHECK (last_seen_at >= first_seen_at)
);


CREATE UNIQUE INDEX IF NOT EXISTS search_history_identity_idx
    ON search_history (user_id, kind, query, filters);


CREATE INDEX IF NOT EXISTS search_history_user_time_idx
    ON search_history (user_id, last_seen_at DESC);



CREATE TABLE IF NOT EXISTS search_log (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    request_id   TEXT        NOT NULL,

    user_id      BIGINT      NOT NULL,          -- 无外键，见上
    kind         TEXT        NOT NULL,
    query        TEXT        NOT NULL DEFAULT '',
    filters      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    page         INTEGER     NOT NULL,
    size         INTEGER     NOT NULL,

    outcome      TEXT        NOT NULL,          -- 'ok' | 'error'
    status_code  INTEGER     NOT NULL,          -- 200 / 400 / 500
    error_type   TEXT,                          -- 异常类名；成功时为 NULL
    result_total INTEGER,
    latency_ms   INTEGER     NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT search_log_outcome_known CHECK (outcome IN ('ok', 'error')),
    CONSTRAINT search_log_ok_is_200     CHECK ((outcome = 'ok') = (status_code = 200)),
    CONSTRAINT search_log_error_typed  CHECK ((outcome = 'ok') = (error_type IS NULL)),
    CONSTRAINT search_log_page_positive  CHECK (page >= 1),
    CONSTRAINT search_log_size_positive  CHECK (size >= 1),
    CONSTRAINT search_log_latency_nonneg CHECK (latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS search_log_time_idx
    ON search_log (created_at DESC);

CREATE INDEX IF NOT EXISTS search_log_user_time_idx
    ON search_log (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS search_log_error_idx
    ON search_log (created_at DESC) WHERE outcome = 'error';


--   DELETE FROM search_log WHERE created_at < now() - interval '90 days'
